[package]
name = "dichonoia-example"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
tokio = { workspace = true, features = ["full"] }

dichonoia.workspace = true
dichonoia-models.workspace = true
