[package]
name = "dichonoia-models"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = { version = "2.10.0", features = ["serde"] }

serde.workspace = true
serde_json.workspace = true
time = { version = "0.3.44", features = ["serde", "serde-well-known"] }
